# Change these first
owner: Fortify-Labs # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: Frontend
    url: https://fortify.gg
  - name: API
    url: https://api.fortify.gg/graphql?query=%7Bversion%7D
  - name: GSI Endpoint
    url: https://gsi.fortify.gg/health
assignees: # Users to assign downtime issues (optional)
  - ThomasK33
notifications:
  - type: discord
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.fortify.gg
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Fortify - Status Monitoring
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
